# Generated by Django 6.0.3 on 2026-04-27 07:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, help_text="Plan cost in USDT.", max_digits=12
                    ),
                ),
                (
                    "duration_days",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="How many days the plan is active after purchase.",
                    ),
                ),
                (
                    "daily_earnings",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Estimated earnings per day in USDT.",
                        max_digits=12,
                    ),
                ),
                (
                    "total_return",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total return over the plan duration.",
                        max_digits=12,
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of feature strings displayed on the plan card.",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Featured plans are highlighted on the plans page.",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Lower numbers appear first. Ties broken by name.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "plan",
                "verbose_name_plural": "plans",
                "ordering": ["sort_order", "name"],
            },
        ),
    ]
