# Generated by Django 6.0.3 on 2026-04-27 08:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentWallet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Display name, e.g. 'Main Deposit Wallet'.",
                        max_length=100,
                    ),
                ),
                (
                    "network",
                    models.CharField(
                        choices=[
                            ("USDT_TRC20", "USDT — TRC20 (Tron)"),
                            ("USDT_ERC20", "USDT — ERC20 (Ethereum)"),
                            ("USDT_BEP20", "USDT — BEP20 (BSC)"),
                        ],
                        default="USDT_TRC20",
                        max_length=20,
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        help_text="The crypto wallet address.", max_length=255
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(db_index=True, default=0),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "payment wallet",
                "verbose_name_plural": "payment wallets",
                "ordering": ["sort_order", "label"],
            },
        ),
        migrations.CreateModel(
            name="PlanPurchase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "plan_name",
                    models.CharField(
                        help_text="Snapshot of plan name at submission time.",
                        max_length=100,
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount user claims to have sent.",
                        max_digits=12,
                    ),
                ),
                (
                    "tx_hash",
                    models.CharField(
                        help_text="Transaction hash / ID provided by user.",
                        max_length=255,
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Optional note from user."),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("admin_note", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment_wallet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchases",
                        to="plans.paymentwallet",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchases",
                        to="plans.plan",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "plan purchase",
                "verbose_name_plural": "plan purchases",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="plans_planp_user_id_53775a_idx"
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="plans_planp_status_1c65cd_idx",
                    ),
                ],
            },
        ),
    ]
