# Generated by Django 6.0.3 on 2026-04-11 12:22

import random
import string
from decimal import Decimal
from django.db import migrations, models


def _gen_code():
    chars = string.ascii_uppercase + string.digits
    return "".join(random.choices(chars, k=8))


def populate_referral_codes(apps, schema_editor):
    """Assign a unique referral code to every existing user."""
    CustomUser = apps.get_model("accounts", "CustomUser")
    existing_codes = set(
        CustomUser.objects.exclude(referral_code="")
        .values_list("referral_code", flat=True)
    )
    for user in CustomUser.objects.filter(referral_code=""):
        code = _gen_code()
        while code in existing_codes:
            code = _gen_code()
        existing_codes.add(code)
        user.referral_code = code
        user.save(update_fields=["referral_code"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_is_email_verified"),
    ]

    operations = [
        # Add referral_code without unique constraint first so backfill can run
        migrations.AddField(
            model_name="customuser",
            name="referral_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=12,
                verbose_name="referral code",
            ),
        ),
        # Backfill unique codes for existing rows
        migrations.RunPython(populate_referral_codes, migrations.RunPython.noop),
        # Now apply the unique constraint
        migrations.AlterField(
            model_name="customuser",
            name="referral_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=12,
                unique=True,
                verbose_name="referral code",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("admin", "Admin")],
                db_index=True,
                default="user",
                max_length=10,
                verbose_name="role",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("banned", "Banned"),
                    ("suspended", "Suspended"),
                ],
                db_index=True,
                default="active",
                max_length=12,
                verbose_name="status",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Optional unique display name / login handle.",
                max_length=50,
                null=True,
                unique=True,
                verbose_name="username",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="vip_level",
            field=models.IntegerField(
                choices=[(0, "Regular"), (1, "VIP 1"), (2, "VIP 2"), (3, "VIP 3")],
                db_index=True,
                default=0,
                verbose_name="VIP level",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="wallet_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="wallet balance",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=models.CharField(
                blank=True, db_index=True, max_length=20, verbose_name="phone number"
            ),
        ),
    ]
