# Generated by Django 6.0.3 on 2026-04-11 12:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VIPPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        db_index=True,
                        help_text="VIP level integer (0 = Regular).",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "min_deposit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Minimum cumulative deposit to reach this level.",
                        max_digits=12,
                    ),
                ),
                (
                    "daily_task_limit",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Maximum tasks a user at this level can complete per day (across all tasks).",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "VIP plan",
                "verbose_name_plural": "VIP plans",
                "ordering": ["level"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("deposit", "Deposit"),
                            ("withdrawal", "Withdrawal"),
                            ("earning", "Earning"),
                            ("bonus", "Bonus"),
                            ("refund", "Refund"),
                        ],
                        db_index=True,
                        max_length=15,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "transaction",
                "verbose_name_plural": "transactions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="wallet_tran_user_id_4e9914_idx",
                    ),
                    models.Index(
                        fields=["user", "type"], name="wallet_tran_user_id_e01378_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Withdrawal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("payment_method", models.CharField(blank=True, max_length=100)),
                ("payment_details", models.JSONField(blank=True, default=dict)),
                ("admin_note", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "withdrawal",
                "verbose_name_plural": "withdrawals",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="wallet_with_user_id_63a0c2_idx"
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="wallet_with_status_e0eee2_idx",
                    ),
                ],
            },
        ),
    ]
