# Generated by Django 6.0.3 on 2026-04-12 18:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0004_manualpayout"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberStory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name, e.g. 'Sarah K.'", max_length=100
                    ),
                ),
                (
                    "avatar_initials",
                    models.CharField(
                        help_text="2–4 letters shown in avatar circle, e.g. 'SK'",
                        max_length=4,
                    ),
                ),
                (
                    "avatar_color",
                    models.CharField(
                        choices=[
                            ("from-violet-500 to-violet-700", "Violet"),
                            ("from-emerald-500 to-emerald-700", "Emerald"),
                            ("from-pink-500 to-pink-700", "Pink"),
                            ("from-amber-500 to-amber-700", "Amber"),
                            ("from-cyan-500 to-cyan-700", "Cyan"),
                            ("from-rose-500 to-rose-700", "Rose"),
                            ("from-blue-500 to-blue-700", "Blue"),
                            ("from-indigo-500 to-indigo-700", "Indigo"),
                            ("from-teal-500 to-teal-700", "Teal"),
                            ("from-orange-500 to-orange-700", "Orange"),
                        ],
                        default="from-violet-500 to-violet-700",
                        help_text="Tailwind gradient for the avatar background.",
                        max_length=60,
                    ),
                ),
                (
                    "earned_amount",
                    models.CharField(
                        help_text="Display string, e.g. '$420'", max_length=20
                    ),
                ),
                (
                    "months_active",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Months active on platform."
                    ),
                ),
                (
                    "quote",
                    models.TextField(
                        help_text="Testimonial text shown on landing page."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Only active stories appear publicly."
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Lower numbers appear first. Ties broken by creation date.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "member story",
                "verbose_name_plural": "member stories",
                "ordering": ["sort_order", "created_at"],
            },
        ),
    ]
