# Generated by Django 6.0.3 on 2026-04-11 12:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        help_text="Step-by-step instructions shown to the user.",
                    ),
                ),
                (
                    "reward_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount credited to the user's wallet on completion.",
                        max_digits=10,
                    ),
                ),
                (
                    "daily_limit",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Maximum number of times a single user may complete this task per day.",
                    ),
                ),
                (
                    "vip_level_required",
                    models.IntegerField(
                        db_index=True,
                        default=0,
                        help_text="Minimum VIP level needed. 0 = open to all users.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "task",
                "verbose_name_plural": "tasks",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "vip_level_required"],
                        name="tasks_task_status_31860a_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TaskCompletion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "earned_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completions",
                        to="tasks.task",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_completions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "task completion",
                "verbose_name_plural": "task completions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "task"], name="tasks_taskc_user_id_1bb82d_idx"
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="tasks_taskc_user_id_807609_idx",
                    ),
                    models.Index(
                        fields=["status"], name="tasks_taskc_status_5c483a_idx"
                    ),
                ],
            },
        ),
    ]
